//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelUploader
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDealerDetail
    {
        public long Id { get; set; }
        public string DealerCode { get; set; }
        public string IMEI { get; set; }
        public string Model { get; set; }
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
        public Nullable<bool> IsSoldOut { get; set; }
    }
}
