//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomUploader
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomUpload
    {
        public long BomUploadId { get; set; }
        public string Model { get; set; }
        public string ProductCode { get; set; }
        public string YwxPartNo { get; set; }
        public string ParentId { get; set; }
        public string Name { get; set; }
        public string ManufacturerPartNo { get; set; }
        public string Description { get; set; }
        public string WaltonPartId { get; set; }
        public string Reference { get; set; }
        public Nullable<long> ReelQty { get; set; }
        public Nullable<long> TotalQty { get; set; }
        public Nullable<long> SetQty { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public string AddedByName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
